server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingmovieticketapp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none  # khong de java tự động tạo bảng, cột, v.v (thay vào đó, sử dụng các cau lệnh SQL để tạo bảng, cột, v.v)
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

tmdb:
  api:
    key: 5fffce961921b470c26eb34749b33ce4