server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingmovieticketapp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none  # khong de java t? ??ng t?o b?ng, cot, v.v (thay vào ?ó, s? d?ng các cau lenh SQL ?? t?o bang, cot, v.v)
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
